login/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView

from .views import *

urlpatterns = [

    path('redefinir_senha/', redefinir_senha, name='redefinir_senha'),
    path('redefinir_senha/ok/', redefinir_senha_ok, name='redefinir_senha_ok'),
    path('redefinir_senha/<uidb64>/<token>/', redefinir_senha_confirmacao, name='redefinir_senha_confirmacao'),
    path('redefinir_senha/completa/', redefinir_senha_completa, name='redefinir_senha_completa'),

]

sistema_medico/urls.py
from django.contrib import admin
from django.urls import path, include
from consulta.views import *
from consulta import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    # HOME. Login and Logout
    # path('login/', logar, name='login'),
    path('', logar, name='login'),
    path('logout/', sair, name='sair'),
    
    # Recuperar senha
    path('login/', include('login.urls')),

    # Cadastro
    path('cadastro/administrativo/', AdministrativoCreate.as_view(), name='administrativoCreate'),
    path('cadastro/profissionaldasaude/', ProfissionaldasaudeCreate.as_view(), name='profissionaldasaudeCreate'),
    path('cadastro/paciente/', PacienteCreate.as_view(), name='pacienteCreate'),
    
    # Agendamento
    path('agendamento/form', AgendamentoCreate.as_view(), name='agendamentoCreate' ),
    path('agendamento/lista', listar_agendamentos, name='agendamentoListagem'),
    path('agendamentos/<int:pk>/confirmar/', agendamento_confirmar, name='agendamentoConfirmar'),
    path('agendamentos/<int:pk>/ausente/', agendamento_ausente, name='agendamentoAusente'),
    path('agendamento/<int:pk>/confirmar/', confirm_agendamento, name='confirmAgendamento'),
    path('agendamento/<int:pk>/download/', download_comprovante, name='downloadComprovante'),
    path('cancelar_agendamento/<int:agendamento_id>/', cancelar_agendamento, name='cancelar_agendamento'),
    path('reagendar/agendamento/<int:pk>/', reagendar_agendamento, name='reagendarAgendamento'),
    path('comprovante/cancelamento/<int:agendamento_id>/', views.pdf_comprovante_cancelamento, name='comprovante_cancelamento'),
    path('agendamentos/cancelados/', listar_agendamentos_cancelados, name='listar_agendamentos_cancelados'),
    
    # Atendimento
    path('atendimento/criar/<int:agendamento_id>', AtendimentoCreate.as_view(), name='criar_atendimento'),
    path('atendimentos/', lista_atendimentos, name='listaAtendimentos'),
    path('atendimento/<int:pk>/', VisualizarAtendimentoView.as_view(), name='visualizarAtendimento'),
    path('confirmar_atendimento/<int:agendamento_id>/', confirmar_atendimento, name='confirmar_atendimento'),

    path('download_comprovante_atendimento/<int:atendimento_id>/', download_comprovante_atendimento,
         name='download_comprovante_atendimento'),

    path('visualizar_comprovante_atendimento/<int:atendimento_id>/', views.visualizar_comprovante_atendimento,
         name='visualizar_comprovante_atendimento'),
    path('registrar_inicio_atendimento/<int:agendamento_id>/', registrar_inicio_atendimento, name='registrar_inicio_atendimento'),
    path('consultas/manter_em_atendimento/<int:agendamento_id>/', views.manter_em_atendimento, name='manter_em_atendimento'),
    path('atendimentos/<int:agendamento_id>/cancelar/', cancelar_atendimento, name='cancelar_atendimento'),
    
    # Prontuario
    path('prontuario_medico/<int:paciente_id>/', views.prontuario_medico, name='prontuario_medico'),
    path('filtrar_prontuarios/', filtrar_prontuarios, name='filtrar_prontuarios'),
    

    #pdfs
    path('visualizar-pdf-exames/<int:atendimento_id>/', views.visualizar_pdf_exames, name='visualizar_pdf_exames'),
    path('pdf_prontuario_medico/<int:paciente_id>/', views.pdf_prontuario_medico, name='pdf_prontuario_medico'),
    path('atendimento/<int:atendimento_id>/atestado/', pdf_atestado_medico, name='pdf_atestado_medico'),
    path('atendimento/<int:atendimento_id>/receita/', pdf_receita_medica, name='pdf_receita_medica'),
    path('pdf_receita_medica/<int:atendimento_id>/<str:tipo>/', pdf_receita_medica, name='pdf_receita_medica_controle'),
    path('pdf_laudo/<int:atendimento_id>/', pdf_laudo_medico, name='pdf_laudo_medico'),


    
    # Listagens
    path('pacientes/', listar_pacientes, name= 'pacienteListagem' ),
    path('profissionaldasaude/', listar_profissionaldasaude, name= 'profissionaldasaudeListagem'),
    path('administrativo/', listar_administrativo, name= 'administrativoListagem'),

    # Edição e Exclusão
    path('paciente/<int:pk>/editar/', paciente_editar, name='pacienteEditar'),
    path('paciente/<int:pk>/excluir/', paciente_excluir, name='pacienteExcluir'),
    path('administrativo/<int:pk>/editar/', administrativo_editar, name='administrativoEditar'),
    path('administrativo/<int:pk>/excluir/', administrativo_excluir, name='administrativoExcluir'),
    path('profissionaldasaude/<int:pk>/editar/', profissionaldasaude_editar, name='profissionaldasaudeEditar'),
    path('profissionaldasaude/<int:pk>/excluir/', profissionaldasaude_excluir, name='profissionaldasaudeExcluir'),
    
    path('editar_administrativo/', views.editar_administrativo, name='editar_administrativo'),#modal editar
    path('editar_paciente/', views.editar_paciente, name='editar_paciente'),#modal editar
    path('editar_profissionaldasaude/', views.editar_profissionaldasaude, name='editar_profissionaldasaude'),#modal editar


    # Restrição de acesso
    path('restricao/', restricao_de_acesso, name='restricao_de_acesso'),
    path('atendimento/<int:atendimento_id>/atualizar_privado/', atualizar_privado, name='atualizar_privado'),
    
    # Excluir arquivos de pacientes enviados em 'Atendimentos'
    path('arquivo/excluir/<int:arquivo_id>/<int:atendimento_id>/', excluir_arquivo, name='excluir_arquivo'),
    
    
    path('search_paciente/', views.search_paciente, name='search_paciente'),
    path('search_profissional/', views.search_profissional, name='search_profissional'),
    
    path('relatorios/', views.obter_relatorios, name='relatorios'),

    # Home
    # path('', views.home, name='home'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

consulta/models.py

from django.conf.global_settings import MEDIA_ROOT
from django.db import models
from datetime import date, datetime
from django.contrib.auth.models import User

from consulta.choices import *

from validate_docbr import CPF
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.utils import timezone
from django.utils.timezone import now


def validate_cpf(value):
    cpf = CPF()
    if not cpf.validate(value):
        raise ValidationError('CPF inválido.')


def data_nasc_valida(value):
    if value > datetime.now().date():
        raise ValidationError('Informe uma data de nascimento válida.')


def arquivos_upload(instance, filename, k):
  import os
  ext = filename.split('.')[-1]
  i = 0
  fn = '/'.join(['arquivos', str(instance.paciente.cpf.replace('.','').replace('-',''))+'_0'+str(k)+'_S'+str(i)+'.'+ext])
  while os.path.exists(MEDIA_ROOT+fn):
    i = i + 1
    fn = '/'.join(['arquivos', str(instance.paciente.cpf.replace('.','').replace('-',''))+'_0'+str(k)+'_S'+str(i)+'.'+ext])
  return fn


def file_up(instance, filename):
  return arquivos_upload(instance, filename, 'arquivo')


class Paciente(models.Model):

    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro') 
    ]
    
    nome = models.CharField(max_length=100)
    nome_social = models.CharField(max_length=100, blank=True, null=True, verbose_name='Nome Social')  
    data_nascimento = models.DateField(verbose_name='Data de Nascimento', validators=[data_nasc_valida], blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    rg = models.CharField(max_length=20, blank=True, null=True)
    cpf = models.CharField(max_length=14, validators=[validate_cpf, MinLengthValidator(11)])
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    matricula = models.CharField(max_length=20)
    TIPO_PACIENTE_CHOICES = [
        ('Aluno', 'Aluno'),
        ('Servidor', 'Servidor'),
        ('Outro', 'Outro'),
    ]

    tipo_paciente = models.CharField(max_length=20, choices=TIPO_PACIENTE_CHOICES)
    cargo_funcao = models.CharField(max_length=50, default='', blank=True, null=True)
    cep = models.CharField(max_length=9, blank=True, null=True)
    cidade = models.CharField(max_length=50, blank=True, null=True)
    bairro = models.CharField(max_length=50, default='', blank=True, null=True)
    uf = models.CharField('UF', max_length=2, choices=UF_CHOICE, default='AC', blank=True, null=True)
    numero = models.CharField(max_length=10, blank=True, null=True)
    ddd_telefone = models.CharField(max_length=8)
    complemento = models.CharField(max_length=100, blank=True, null=True, default='')  # Adicionando o valor padrão aqui

    def save(self, *args, **kwargs):
        # Se o sexo não for fornecido, defina-o como None
        if not self.sexo:
            self.sexo = None
        super().save(*args, **kwargs)


    def __str__(self):
        return self.get_display_name()
    
    def get_display_name(self):
        if self.nome_social:
            return f"{self.nome} ({self.nome_social})"
        return self.nome
    
    def idade(self):
        today = date.today()
        age = today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return age 

def validate_unique_cpf(value):
    if Administrativo.objects.filter(cpf=value).exists():
        raise ValidationError('CPF já cadastrado.')

def validate_unique_email(value):
    if Administrativo.objects.filter(email=value).exists():
        raise ValidationError('Email já cadastrado.')

class Administrativo(models.Model):
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro') 
    ]
    
    usuario = models.OneToOneField(User, on_delete=models.SET_NULL, blank=True, null=True)
    nome = models.CharField(max_length=100, verbose_name='Nome Completo')
    nome_social = models.CharField(max_length=100, blank=True, null=True, verbose_name='Nome Social')  
    data_nascimento = models.DateField(verbose_name='Data de nascimento', validators=[data_nasc_valida])
    email = models.EmailField()
    rg = models.CharField(max_length=20)
    cpf = models.CharField(max_length=14, validators=[validate_cpf, MinLengthValidator(11)])
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    cargo_funcao = models.CharField(max_length=50, default='')
    cep = models.CharField(max_length=9)
    cidade = models.CharField(max_length=50)
    bairro = models.CharField(max_length=50, default='')
    uf = models.CharField('UF', max_length=2, choices=UF_CHOICE, default='AC')
    numero = models.CharField(max_length=10)
    ddd_telefone = models.CharField('Telefone Celular', max_length=14, help_text='Com DDD.')
    complemento = models.CharField(max_length=100, blank=True, null=True, default='')
    lotacao_de_exercicio = models.CharField(max_length=50, default='')
    matricula_siape = models.CharField(max_length=20)

    def __str__(self):
        return self.get_display_name()
    
    def get_display_name(self):
        return self.nome_social if self.nome_social else self.nome
    
    def idade(self):
        today = date.today()
        age = today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return age 

    class Meta:
        ordering = ['-nome']
        verbose_name = 'Administrativo'
        verbose_name_plural = 'Administrativo'

    
class Profissionaldasaude(models.Model):
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro') 
    ]
    usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    nome = models.CharField('Nome Completo', max_length=100)
    nome_social = models.CharField(max_length=100, blank=True, null=True, verbose_name='Nome Social')  
    data_nascimento = models.DateField(u'Data de Nascimento', validators=[data_nasc_valida])
    email = models.EmailField()
    rg = models.CharField(max_length=20)
    cpf = models.CharField(max_length=14, validators=[validate_cpf, MinLengthValidator(11)])
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    identificacao_unica = models.CharField(max_length=50, default='')
    cep = models.CharField(max_length=9)
    cidade = models.CharField(max_length=50)
    bairro = models.CharField(max_length=50, default='')
    uf = models.CharField('UF', max_length=2, choices=UF_CHOICE, default='AC')
    numero = models.CharField(max_length=10)
    ddd_telefone = models.CharField('Telefone Celular', max_length=14, help_text='Com DDD.')
    complemento = models.CharField(max_length=100, blank=True, null=True, default='') # blank=True, null=True é pra dizer que não é obrigatorio 
    area = models.CharField(max_length=50, default='')
    unidade_siass = models.CharField(max_length=50, default='')
    formacao = models.CharField(max_length=20)
    conselho = models.CharField(max_length=20)
    registro = models.CharField(max_length=20)


    def __str__(self):
        return self.get_display_name()
    
    def get_display_name(self):
        if self.nome_social:
            return f"{self.nome} ({self.nome_social})"
        return self.nome
    
    def idade(self):
        today = date.today()
        age = today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return age 

    class Meta:
        # db_table = 'PROFISSIONALDASAUDE'
        ordering = ['nome', ]
        verbose_name = 'Profissonal de saúde'
        verbose_name_plural = 'Profissonais de saúde'


class Agendamento(models.Model):
    TURNO_CHOICES = [
        ('manha', 'Manhã'),
        ('tarde', 'Tarde'),
    ]

    status_atendimento = models.CharField(max_length=20, choices=[
        ('confirmado', 'Confirmado'),
        ('ausente', 'Ausente'),
        ('pendente', 'Pendente'),
        ('cancelado', 'Cancelado'),
        ('atendido', 'Atendido'),
    ], default='pendente')
    paciente = models.ForeignKey('Paciente', on_delete=models.CASCADE)
    profissional_saude = models.ForeignKey('Profissionaldasaude', on_delete=models.CASCADE)
    data_agendamento = models.DateField('Data Agendamento', blank=False, null=False)
    turno = models.CharField(max_length=10, choices=TURNO_CHOICES)
    prioridade_atendimento = models.BooleanField(default=False)
    justificativa_cancelamento = models.TextField(blank=True, null=True)
    inicio_atendimento = models.DateTimeField(null=True, blank=True)
    horario_confirmacao = models.DateTimeField(null=True, blank=True)
    horario_cancelamento = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Agendamento para {self.paciente.nome}"

    def atualizar_status(self):
        now = timezone.now().date()
        
        # Garantir que data_agendamento não é None antes de comparar
        if self.data_agendamento and self.data_agendamento < now:
            if self.status_atendimento not in ['atendido', 'confirmado']:
                self.status_atendimento = 'ausente'
            self.save()
    
    def cancelar_pend_confir(self):
        return self.status_atendimento in ['pendente', 'confirmado']
    
    def confirmar(self):
        """Confirma o agendamento e registra o horário."""
        self.status_atendimento = 'confirmado'
        self.horario_confirmacao = now()
        self.save()

    def cancelar(self, justificativa):
        """Cancela o agendamento/atendimento e registra o horário e justificativa."""
        self.status_atendimento = 'cancelado'

login/forms.py
# -*- coding: UTF-8 -*-


from django.contrib.auth.models import User
from django.forms import *
from django import forms



# Form para manipulação personalizada
class AlterarSenhaForm(forms.Form):
    email = CharField(widget=forms.TextInput(attrs={'autofocus': True}))

    def __init__(self, *args, **kwargs):
        super(AlterarSenhaForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class'] = 'form-control'

templates/consultas/confirm_agendamento.html
<!-- consulta/templates/consulta/confirm_agendamento.html -->
{% extends "base.html" %}

{% block title %}Confirmação de Agendamento{% endblock %}

{% block content %}
    {#    {% load static %}#}

    {#  Verifica se há message na views e mostra caso true  #}
    {#{% if messages %}{% include 'messages.html' %}{% endif %}#}

    
    <div class="container">
        <div class="col-md-8 offset-md-2">

            <div class=" card border-primary card-body table-responsive">
                <h2 class="text-center mb-3 text-bg-primary " style="padding: 10px 0">Confirmação de Agendamento</h2>
                <hr>
                <table class="table table-striped table-bordered table-responsive">
                    <thead>
                    <tr>
                        <th style="vertical-align: top">Paciente:</th> <br>
                        <th>Profissional de Saúde:</th>
                        <th>Data da Consulta:</th>

                        <th style="vertical-align: top">Turno:</th> <br>
                        <th>Prioridade de Atendimento:</th>
                        
                        <br>
                        
                    </tr>
                    </thead>

                    <tbody>
                    <tr>
                        <td><span>{{ agendamento.paciente.get_display_name }}</span>
                        <td><span>{{ agendamento.profissional_saude.get_display_name }}</span></td>


                        <td><span>{{ agendamento.data_agendamento|date:"d/m/Y" }}</span></td>
                        <td><span>{{ agendamento.get_turno_display }}</span></td>
                        <td>
                            {% if agendamento.prioridade_atendimento %}
                                <span style="color: green">Sim&nbsp;<i class="fa fa-check-circle"></i></span>
                            {% else %}
                                <span style="color: red">Não&nbsp;<i class="fa fa-close"></i></span>
                            {% endif %}
                        </td>
                    </tr>
                    </tbody>
                </table>

                <div class="d-flex justify-content-between mt-2">
                    <a type="submit" class="btn btn-primary btn-sm" style="margin-bottom: 2px"
                       methods="POST" href="{% url 'downloadComprovante' pk=agendamento.pk %}" target="_blank">
                        Baixar Comprovante &nbsp;<i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                    </a>
                    <a style="justify-content: right; margin-bottom: 2px" class="btn btn-warning"
                       href="{% url 'agendamentoListagem' %}">
                        <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>&nbsp;Retornar
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/consultas/confirmar_atendimento.html
<!-- consulta/templates/consulta/confirmar_atendimento.html -->
{% extends 'base.html' %}

{% block title %}
  Confirmação de Atendimento
{% endblock %}

{% block content %}
  {# Verifica se há mensagens na view e mostra, caso existam #}
  {% if messages %}{% include 'messages.html' %}{% endif %}

  <div class="container">
    <h2 class="text-center mb-4 text-black">CONFIRMAÇÃO DE ATENDIMENTO</h2>
    <div class="p-4" id="glass">
        <div class="card p-4">
            <div class="infos">
                <p><strong>Paciente:</strong> {{ atendimento.agendamento.paciente.get_display_name }}</p>
                <p><strong>Profissional de Saúde:</strong> {{ atendimento.agendamento.profissional_saude.get_display_name }}</p>
                <p><strong>Data do Atendimento:</strong> {{ atendimento.data_atendimento|date:'d/m/Y' }}</p>
                <p><strong>Início do Atendimento:</strong> {{ atendimento.inicio_atendimento|date:"d/m/Y às H:i" }}</p>
                <p><strong>Fim do Atendimento:</strong> {{ atendimento.fim_atendimento|date:"d/m/Y às H:i" }}</p>
                <p><strong>Duração do Atendimento:</strong> {{ atendimento.duracao_atendimento }}</p>
            </div> 

            <div class="d-flex justify-content-between mt-2">
                <a type="submit" class="btn btn-primary btn-sm" href="{% url 'download_comprovante_atendimento' atendimento_id=atendimento.pk %}">
                    Baixar Comprovante &nbsp;<i class="fa fa-file-pdf-o"></i>
                </a>

                {% if receita_simples %}
                <a href="{% url 'pdf_receita_medica' atendimento.id %}" target="_blank" class="print-btn text-decoration-none">
                    <button class="print-btn">Imprimir Receita Simples</button>
                </a>
                {% endif %}

                {% if receita_controle_especial %}
                <a href="{% url 'pdf_receita_medica_controle' atendimento.id 'controle_especial' %}" target="_blank" class="print-btn text-decoration-none">
                    <button class="print-btn">Imprimir Receita de Controle Especial</button>
                </a>
                {% endif %}

                {% if receita_simples or receita_controle_especial %}
                <a href="{% url 'pdf_atestado_medico' atendimento.id %}" target="_blank" class="print-btn text-decoration-none">
                    <button class="print-btn">Imprimir Atestado</button>
                </a>
                {% endif %}

                {% if laudos %}
                <a href="{% url 'pdf_laudo_medico' atendimento.id %}" target="_blank" class="print-btn text-decoration-none">
                    <button class="print-btn">Imprimir Laudo</button>
                </a>
                {% endif %}

                <a class="btn btn-warning" href="{% url 'agendamentoListagem' %}">
                    <i class="fa fa-arrow-circle-left text-decoration-none"></i>&nbsp;Voltar para agendamento
                </a>
            </div>
        </div>
    </div>
</div>



  <style>
    .infos{
        display: flex;
        justify-content: space-between;
        border-bottom: 1px solid #ccc;
    }
  </style>
{% endblock %}

templates/consultas/editar_administrativo.html
{% extends 'base.html' %}

{% block title %}
  Editar profissional Administrativo
{% endblock %}

{% block content %}
  {% if messages %}{% include 'messages.html' %}{% endif %}

  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="">
        <div class=" mb-4">
          <h4 class="text-center mb-3 text-black">EDITAR PROFISSIONAL ADMINISTRATIVO</h4>
        </div>

        <div class="col-md-10 offset-md-1 mb-2">
          <div class="m-2">
            <form action="{% url 'administrativoEditar' administrativo.id %}" method="POST" id="glass">
              {% csrf_token %}

              <div class="m-4">
                <div class="m-2">
                  <div class="col-sm-12" id="pessoais">
                    <div class="col mb-3">
                      <label for="{{ form.nome.id_for_label }}" class="col-sm-2 col-form-label"><b>Nome</b></label>
                      <div class="col-sm-12">{{ form.nome }}</div>
                    </div>

                    <div class="col mb-3">
                      <label for="{{ form.email.id_for_label }}" class="col-sm-2 col-form-label"><b>E-mail</b></label>
                      <div class="col-sm-12">
                        {% with field=form.email %}
                          {% include 'field.html' %}
                        {% endwith %}
                      </div>
                    </div>

                    <div class="row mb-3">
                      <div class="col-sm-6">
                        <label for="{{ form.cpf.id_for_label }}" class="col-sm-2 col-form-label"><b>CPF</b></label>
                        <div class="col-sm-12">
                          {% with field=form.cpf %}
                            {% include 'field.html' %}
                          {% endwith %}
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <label for="{{ form.rg.id_for_label }}" class="col-sm-2 col-form-label"><b>RG</b></label>
                        <div class="col-sm-12">{{ form.rg }}</div>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <div class="col-sm-6">
                        <label for="{{ form.data_nascimento.id_for_label }}" class="col-sm-6 col-form-label"><b>Data de Nascimento</b></label>
                        <div class="col-sm-12">
                          {% with field=form.data_nascimento %}
                            {% include 'field.html' %}
                          {% endwith %}
                        </div>
                      </div>

                      <div class="col-sm-6">
                        <label for="{{ form.sexo.id_for_label }}" class="col-sm-2 col-form-label"><b>Sexo</b></label>
                        <div class="col-sm-12">{{ form.sexo }}</div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-12" id="endereco">
                    <div class="col mb-3">
                      <label for="{{ form.bairro.id_for_label }}" class="col-sm-2 col-form-label"><b>Bairro e Rua</b></label>
                      <div class="col-sm-12">{{ form.bairro }}</div>
                    </div>

                    <div class="row mb-3">
                      <div class="col-sm-6">
                        <label for="{{ form.numero.id_for_label }}" class="col-sm-2 col-form-label"><b>Número</b></label>
                        <div class="col-sm-12">{{ form.numero }}</div>
                      </div>
                      <div class="col-sm-6">
                        <label for="{{ form.cidade.id_for_label }}" class="col-sm-2 col-form-label"><b>Cidade</b></label>
                        <div class="col-sm-12">{{ form.cidade }}</div>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <div class="col-sm-6">
                        <label for="{{ form.uf.id_for_label }}" class="col-sm-2 col-form-label"><b>UF</b></label>
                        <div class="col-sm-12">{{ form.uf }}</div>
                      </div>
                      <div class="col-sm-6">
                        <label for="{{ form.cep.id_for_label }}" class="col-sm-2 col-form-label"><b>CEP</b></label>
                        <div class="col-sm-12">{{ form.cep }}</div>
                      </div>
                    </div>

                    <div class="col mb-3">
                      <label for="{{ form.ddd_telefone.id_for_label }}" class="col-sm-2 col-form-label"><b>Telefone</b></label>
                      <div class="col-sm-12">{{ form.ddd_telefone }}</div>
                    </div>

                    <div class="col mb-3">
                      <label for="{{ form.complemento.id_for_label }}" class="col-sm-2 col-form-label"><b>Complemento</b></label>
                      <div class="col-sm-12">{{ form.complemento }}</div>
                    </div>
                  </div>

                  <div class="col-sm-12" id="cargo">
                    <div class="mb-3 row">
                      <label for="{{ form.cargo_funcao.id_for_label }}" class="col-sm-2 col-form-label"><b>Cargo/Função</b></label>
                      <div class="col-sm-12">{{ form.cargo_funcao }}</div>
                    </div>

                    <div class="row mb-3">
                      <div class="col-sm-6">
                        <label for="{{ form.lotacao_de_exercicio.id_for_label }}" class="col-sm-12 col-form-label"><b>Lotação de Exercício</b></label>
                        <div class="col-sm-12">{{ form.lotacao_de_exercicio }}</div>
                      </div>
                      <div class="col-sm-6">
                        <label for="{{ form.matricula_siape.id_for_label }}" class="col-sm-12 col-form-label"><b>Matricula Siape</b></label>
                        <div class="col-sm-12">{{ form.matricula_siape }}</div>
                      </div>
                    </div>
                  </div>
                  <br />

                  <div class="mb-3 row">
                    <div class="text-center">
                      <button type="submit" class="btn btn-primary"><b>Salvar Alterações</b></button>
                      <a href="{% url 'administrativoListagem' %}" class="btn btn-secondary" style="line-height: 2; margin-bottom: 2px"><b>Cancelar</b></a>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% comment %} <style>

    label[for="id_sexo_0"] {
        display: none;
    }

    label[for="id_sexo_1"], label[for="id_sexo_2"] {
        display: flex;
        margin-bottom: 10px;
    }

    #id_sexo_0, #id_sexo_1, #id_sexo_2{
        display: flex;
        flex-direction: row;
        width: 0px;
        border-radius: 100%;
        padding-bottom: 20px;
        margin-right: 10px;
    }
    #id_sexo{
        display: flex;
        flex-direction: column;
        justify-content: space-evenly;
        background-color: transparent;
        border: none;

    }
</style> {% endcomment %}
{% endblock %}