login/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView

from .views import *

urlpatterns = [

    path('redefinir_senha/', redefinir_senha, name='redefinir_senha'),
    path('redefinir_senha/ok/', redefinir_senha_ok, name='redefinir_senha_ok'),
    path('redefinir_senha/<uidb64>/<token>/', redefinir_senha_confirmacao, name='redefinir_senha_confirmacao'),
    path('redefinir_senha/completa/', redefinir_senha_completa, name='redefinir_senha_completa'),

]

sistema_medico/urls.py
from django.contrib import admin
from django.urls import path, include
from consulta.views import *
from consulta import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    # HOME. Login and Logout
    # path('login/', logar, name='login'),
    path('', logar, name='login'),
    path('logout/', sair, name='sair'),
    
    # Recuperar senha
    path('login/', include('login.urls')),

    # Cadastro
    path('cadastro/administrativo/', AdministrativoCreate.as_view(), name='administrativoCreate'),
    path('cadastro/profissionaldasaude/', ProfissionaldasaudeCreate.as_view(), name='profissionaldasaudeCreate'),
    path('cadastro/paciente/', PacienteCreate.as_view(), name='pacienteCreate'),
    
    # Agendamento
    path('agendamento/form', AgendamentoCreate.as_view(), name='agendamentoCreate' ),
    path('agendamento/lista', listar_agendamentos, name='agendamentoListagem'),
    path('agendamentos/<int:pk>/confirmar/', agendamento_confirmar, name='agendamentoConfirmar'),
    path('agendamentos/<int:pk>/ausente/', agendamento_ausente, name='agendamentoAusente'),
    path('agendamento/<int:pk>/confirmar/', confirm_agendamento, name='confirmAgendamento'),
    path('agendamento/<int:pk>/download/', download_comprovante, name='downloadComprovante'),
    path('cancelar_agendamento/<int:agendamento_id>/', cancelar_agendamento, name='cancelar_agendamento'),
    path('reagendar/agendamento/<int:pk>/', reagendar_agendamento, name='reagendarAgendamento'),
    path('comprovante/cancelamento/<int:agendamento_id>/', views.pdf_comprovante_cancelamento, name='comprovante_cancelamento'),
    path('agendamentos/cancelados/', listar_agendamentos_cancelados, name='listar_agendamentos_cancelados'),
    
    # Atendimento
    path('atendimento/criar/<int:agendamento_id>', AtendimentoCreate.as_view(), name='criar_atendimento'),
    path('atendimentos/', lista_atendimentos, name='listaAtendimentos'),
    path('atendimento/<int:pk>/', VisualizarAtendimentoView.as_view(), name='visualizarAtendimento'),
    path('confirmar_atendimento/<int:agendamento_id>/', confirmar_atendimento, name='confirmar_atendimento'),

    path('download_comprovante_atendimento/<int:atendimento_id>/', download_comprovante_atendimento,
         name='download_comprovante_atendimento'),

    path('visualizar_comprovante_atendimento/<int:atendimento_id>/', views.visualizar_comprovante_atendimento,
         name='visualizar_comprovante_atendimento'),
    path('registrar_inicio_atendimento/<int:agendamento_id>/', registrar_inicio_atendimento, name='registrar_inicio_atendimento'),
    path('consultas/manter_em_atendimento/<int:agendamento_id>/', views.manter_em_atendimento, name='manter_em_atendimento'),
    path('atendimentos/<int:agendamento_id>/cancelar/', cancelar_atendimento, name='cancelar_atendimento'),
    
    # Prontuario
    path('prontuario_medico/<int:paciente_id>/', views.prontuario_medico, name='prontuario_medico'),
    path('filtrar_prontuarios/', filtrar_prontuarios, name='filtrar_prontuarios'),
    

    #pdfs
    path('visualizar-pdf-exames/<int:atendimento_id>/', views.visualizar_pdf_exames, name='visualizar_pdf_exames'),
    path('pdf_prontuario_medico/<int:paciente_id>/', views.pdf_prontuario_medico, name='pdf_prontuario_medico'),
    path('atendimento/<int:atendimento_id>/atestado/', pdf_atestado_medico, name='pdf_atestado_medico'),
    path('atendimento/<int:atendimento_id>/receita/', pdf_receita_medica, name='pdf_receita_medica'),
    path('pdf_receita_medica/<int:atendimento_id>/<str:tipo>/', pdf_receita_medica, name='pdf_receita_medica_controle'),
    path('pdf_laudo/<int:atendimento_id>/', pdf_laudo_medico, name='pdf_laudo_medico'),


    
    # Listagens
    path('pacientes/', listar_pacientes, name= 'pacienteListagem' ),
    path('profissionaldasaude/', listar_profissionaldasaude, name= 'profissionaldasaudeListagem'),
    path('administrativo/', listar_administrativo, name= 'administrativoListagem'),

    # Edição e Exclusão
    path('paciente/<int:pk>/editar/', paciente_editar, name='pacienteEditar'),
    path('paciente/<int:pk>/excluir/', paciente_excluir, name='pacienteExcluir'),
    path('administrativo/<int:pk>/editar/', administrativo_editar, name='administrativoEditar'),
    path('administrativo/<int:pk>/excluir/', administrativo_excluir, name='administrativoExcluir'),
    path('profissionaldasaude/<int:pk>/editar/', profissionaldasaude_editar, name='profissionaldasaudeEditar'),
    path('profissionaldasaude/<int:pk>/excluir/', profissionaldasaude_excluir, name='profissionaldasaudeExcluir'),
    
    path('editar_administrativo/', views.editar_administrativo, name='editar_administrativo'),#modal editar
    path('editar_paciente/', views.editar_paciente, name='editar_paciente'),#modal editar
    path('editar_profissionaldasaude/', views.editar_profissionaldasaude, name='editar_profissionaldasaude'),#modal editar


    # Restrição de acesso
    path('restricao/', restricao_de_acesso, name='restricao_de_acesso'),
    path('atendimento/<int:atendimento_id>/atualizar_privado/', atualizar_privado, name='atualizar_privado'),
    
    # Excluir arquivos de pacientes enviados em 'Atendimentos'
    path('arquivo/excluir/<int:arquivo_id>/<int:atendimento_id>/', excluir_arquivo, name='excluir_arquivo'),
    
    
    path('search_paciente/', views.search_paciente, name='search_paciente'),
    path('search_profissional/', views.search_profissional, name='search_profissional'),
    
    path('relatorios/', views.obter_relatorios, name='relatorios'),

    # Home
    # path('', views.home, name='home'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

consulta/models.py

from django.conf.global_settings import MEDIA_ROOT
from django.db import models
from datetime import date, datetime
from django.contrib.auth.models import User

from consulta.choices import *

from validate_docbr import CPF
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.utils import timezone
from django.utils.timezone import now


def validate_cpf(value):
    cpf = CPF()
    if not cpf.validate(value):
        raise ValidationError('CPF inválido.')


def data_nasc_valida(value):
    if value > datetime.now().date():
        raise ValidationError('Informe uma data de nascimento válida.')


def arquivos_upload(instance, filename, k):
  import os
  ext = filename.split('.')[-1]
  i = 0
  fn = '/'.join(['arquivos', str(instance.paciente.cpf.replace('.','').replace('-',''))+'_0'+str(k)+'_S'+str(i)+'.'+ext])
  while os.path.exists(MEDIA_ROOT+fn):
    i = i + 1
    fn = '/'.join(['arquivos', str(instance.paciente.cpf.replace('.','').replace('-',''))+'_0'+str(k)+'_S'+str(i)+'.'+ext])
  return fn


def file_up(instance, filename):
  return arquivos_upload(instance, filename, 'arquivo')


class Paciente(models.Model):

    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro') 
    ]
    
    nome = models.CharField(max_length=100)
    nome_social = models.CharField(max_length=100, blank=True, null=True, verbose_name='Nome Social')  
    data_nascimento = models.DateField(verbose_name='Data de Nascimento', validators=[data_nasc_valida], blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    rg = models.CharField(max_length=20, blank=True, null=True)
    cpf = models.CharField(max_length=14, validators=[validate_cpf, MinLengthValidator(11)])
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    matricula = models.CharField(max_length=20)
    TIPO_PACIENTE_CHOICES = [
        ('Aluno', 'Aluno'),
        ('Servidor', 'Servidor'),
        ('Outro', 'Outro'),
    ]

    tipo_paciente = models.CharField(max_length=20, choices=TIPO_PACIENTE_CHOICES)
    cargo_funcao = models.CharField(max_length=50, default='', blank=True, null=True)
    cep = models.CharField(max_length=9, blank=True, null=True)
    cidade = models.CharField(max_length=50, blank=True, null=True)
    bairro = models.CharField(max_length=50, default='', blank=True, null=True)
    uf = models.CharField('UF', max_length=2, choices=UF_CHOICE, default='AC', blank=True, null=True)
    numero = models.CharField(max_length=10, blank=True, null=True)
    ddd_telefone = models.CharField(max_length=8)
    complemento = models.CharField(max_length=100, blank=True, null=True, default='')  # Adicionando o valor padrão aqui

    def save(self, *args, **kwargs):
        # Se o sexo não for fornecido, defina-o como None
        if not self.sexo:
            self.sexo = None
        super().save(*args, **kwargs)


    def __str__(self):
        return self.get_display_name()
    
    def get_display_name(self):
        if self.nome_social:
            return f"{self.nome} ({self.nome_social})"
        return self.nome
    
    def idade(self):
        today = date.today()
        age = today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return age 

def validate_unique_cpf(value):
    if Administrativo.objects.filter(cpf=value).exists():
        raise ValidationError('CPF já cadastrado.')

def validate_unique_email(value):
    if Administrativo.objects.filter(email=value).exists():
        raise ValidationError('Email já cadastrado.')

class Administrativo(models.Model):
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro') 
    ]
    
    usuario = models.OneToOneField(User, on_delete=models.SET_NULL, blank=True, null=True)
    nome = models.CharField(max_length=100, verbose_name='Nome Completo')
    nome_social = models.CharField(max_length=100, blank=True, null=True, verbose_name='Nome Social')  
    data_nascimento = models.DateField(verbose_name='Data de nascimento', validators=[data_nasc_valida])
    email = models.EmailField()
    rg = models.CharField(max_length=20)
    cpf = models.CharField(max_length=14, validators=[validate_cpf, MinLengthValidator(11)])
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    cargo_funcao = models.CharField(max_length=50, default='')
    cep = models.CharField(max_length=9)
    cidade = models.CharField(max_length=50)
    bairro = models.CharField(max_length=50, default='')
    uf = models.CharField('UF', max_length=2, choices=UF_CHOICE, default='AC')
    numero = models.CharField(max_length=10)
    ddd_telefone = models.CharField('Telefone Celular', max_length=14, help_text='Com DDD.')
    complemento = models.CharField(max_length=100, blank=True, null=True, default='')
    lotacao_de_exercicio = models.CharField(max_length=50, default='')
    matricula_siape = models.CharField(max_length=20)

    def __str__(self):
        return self.get_display_name()
    
    def get_display_name(self):
        return self.nome_social if self.nome_social else self.nome
    
    def idade(self):
        today = date.today()
        age = today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return age 

    class Meta:
        ordering = ['-nome']
        verbose_name = 'Administrativo'
        verbose_name_plural = 'Administrativo'

    
class Profissionaldasaude(models.Model):
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro') 
    ]
    usuario = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    nome = models.CharField('Nome Completo', max_length=100)
    nome_social = models.CharField(max_length=100, blank=True, null=True, verbose_name='Nome Social')  
    data_nascimento = models.DateField(u'Data de Nascimento', validators=[data_nasc_valida])
    email = models.EmailField()
    rg = models.CharField(max_length=20)
    cpf = models.CharField(max_length=14, validators=[validate_cpf, MinLengthValidator(11)])
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    identificacao_unica = models.CharField(max_length=50, default='')
    cep = models.CharField(max_length=9)
    cidade = models.CharField(max_length=50)
    bairro = models.CharField(max_length=50, default='')
    uf = models.CharField('UF', max_length=2, choices=UF_CHOICE, default='AC')
    numero = models.CharField(max_length=10)
    ddd_telefone = models.CharField('Telefone Celular', max_length=14, help_text='Com DDD.')
    complemento = models.CharField(max_length=100, blank=True, null=True, default='') # blank=True, null=True é pra dizer que não é obrigatorio 
    area = models.CharField(max_length=50, default='')
    unidade_siass = models.CharField(max_length=50, default='')
    formacao = models.CharField(max_length=20)
    conselho = models.CharField(max_length=20)
    registro = models.CharField(max_length=20)


    def __str__(self):
        return self.get_display_name()
    
    def get_display_name(self):
        if self.nome_social:
            return f"{self.nome} ({self.nome_social})"
        return self.nome
    
    def idade(self):
        today = date.today()
        age = today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))
        return age 

    class Meta:
        # db_table = 'PROFISSIONALDASAUDE'
        ordering = ['nome', ]
        verbose_name = 'Profissonal de saúde'
        verbose_name_plural = 'Profissonais de saúde'


class Agendamento(models.Model):
    TURNO_CHOICES = [
        ('manha', 'Manhã'),
        ('tarde', 'Tarde'),
    ]

    status_atendimento = models.CharField(max_length=20, choices=[
        ('confirmado', 'Confirmado'),
        ('ausente', 'Ausente'),
        ('pendente', 'Pendente'),
        ('cancelado', 'Cancelado'),
        ('atendido', 'Atendido'),
    ], default='pendente')
    paciente = models.ForeignKey('Paciente', on_delete=models.CASCADE)
    profissional_saude = models.ForeignKey('Profissionaldasaude', on_delete=models.CASCADE)
    data_agendamento = models.DateField('Data Agendamento', blank=False, null=False)
    turno = models.CharField(max_length=10, choices=TURNO_CHOICES)
    prioridade_atendimento = models.BooleanField(default=False)
    justificativa_cancelamento = models.TextField(blank=True, null=True)
    inicio_atendimento = models.DateTimeField(null=True, blank=True)
    horario_confirmacao = models.DateTimeField(null=True, blank=True)
    horario_cancelamento = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Agendamento para {self.paciente.nome}"

    def atualizar_status(self):
        now = timezone.now().date()
        
        # Garantir que data_agendamento não é None antes de comparar
        if self.data_agendamento and self.data_agendamento < now:
            if self.status_atendimento not in ['atendido', 'confirmado']:
                self.status_atendimento = 'ausente'
            self.save()
    
    def cancelar_pend_confir(self):
        return self.status_atendimento in ['pendente', 'confirmado']
    
    def confirmar(self):
        """Confirma o agendamento e registra o horário."""
        self.status_atendimento = 'confirmado'
        self.horario_confirmacao = now()
        self.save()

    def cancelar(self, justificativa):
        """Cancela o agendamento/atendimento e registra o horário e justificativa."""
        self.status_atendimento = 'cancelado'

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Seu Título Aqui
      {% endblock %}
    </title>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    {# Bootstrap versão 5.3.2 CSS #}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap5.3.2/css/bootstrap.css' %}" />

    {# CSS #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}" />
    <link rel="stylesheet" href="{% static 'font-awesome-4.6.3/css/font-awesome.css' %}" />

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.bootstrap5.min.css" />

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  </head>

  <body style="min-height: 100vh; display: flex; flex-direction: column;">
    {# Inclui o cabeçalho das páginas #}
    {% include 'linha_usuario.html' %}

    <div class="container mt-5" style="flex: 1;">
      {% comment %} {% block messages %}
        {% if messages %}
          <div class="alert alert-success" role="alert">{{ messages }}</div>
        {% endif %}
      {% endblock %} {% endcomment %}
      {% block content %}

      {% endblock %}
    </div>

    {# loading #}
    <div class="loading" id="loading-screen" style="display: none;" >
      <svg width="64px" height="48px">
        <polyline points="0.157 23.954, 14 23.954, 21.843 48, 43 0, 50 24, 64 24" id="back"></polyline>
        <polyline points="0.157 23.954, 14 23.954, 21.843 48, 43 0, 50 24, 64 24" id="front"></polyline>
      </svg>
    </div>

    <footer class="text-center mt-4" style="background-color: #0C4DA2; color: white; padding: 10px;">
      <p>&copy; {{ year }} Universidade Federal do Acre | Rodovia BR 364, km 04 | Email: medico@.com | Telefone: 68999212325</p>
    </footer>

    {# Bootstrap versão 5.3.2 JavaScript #}
    <script src="{% static 'bootstrap5.3.2/js/bootstrap.bundle.min.js' %}"></script>

    {# Maskedput #}
    <script type="text/javascript" src="{% static 'jquery/jquery.mask.min.js' %}"></script>

    {# DataTables JavaScript #}
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/responsive.bootstrap5.min.js"></script>

    {# loader #}

    <script>
      function showLoading() {
        document.getElementById("loading-screen").style.display = "flex";
      }
      
      function hideLoading() {
        document.getElementById("loading-screen").style.display = "none";
      }
    </script>

    <script>
        {# Máscara de formatação Jquery #}
        $(function ($) {
            //{#$('#id_data_agendamento').mask('99/99/9999');#}
            $('#id_data_nascimento').mask('99/99/9999');
            $("#id_cep").mask("99999-999");
        });

        {# Botão de voltar ao topo #}
        if ($('#btnTopo').length > 0) {
            window.onscroll = function () {
                scroll();
            }

            function scroll() {
                var btn = document.getElementById("btnTopo");
                if (document.documentElement.scrollTop > 100) {
                    btn.style.display = "block";
                } else {
                    btn.style.display = "none";
                }
            }

            function voltarTopo() {
                document.documentElement.scrollTop = 0;
            }
        }

        {# Desaparecer Messages automaticamente #}
        setTimeout(function () {
            $(".alert").fadeOut("slow", function () {
                $(this).alert("close");
            });
        }, 4000);

        setTimeout(function () {
            $(".errorlist").fadeOut("slow", function () {
                $(this).alert("close");
            });
        }, 6000);
    </script>

    <script>

        {# Calendário #}
        $(document).ready(function () {
            $("#id_data_agendamento").datepicker({
                dateFormat: 'dd/mm/yy'
            });
        });


        {# Inicializando Tooltip. #}
        {# Forma 01 #}
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
        
        {# Forma 02 #}
        $(function () {
            $(".btn").tooltip();
        });
    
        {# Forma 03 - bootstrap5#}
        document.addEventListener('DOMContentLoaded', function () {
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
                return new bootstrap.Tooltip(tooltipTriggerEl)
            })
        });
        

    </script>
  </body>
</html>

templates/field.html
{# RETORNA MENSAGENS DE ERROS #}

{{ field }}
{% if field.errors %}
    <div class=" alert alert-danger text-center" style="padding: 5px; margin-top: 3px" >


        {{ field.errors|striptags }}

    </div>
{% endif %}

templates/home.html
<!-- home.html -->
{% extends "base.html" %}


<style type="text/css">

   style {
       background-color: red;
   }

</style>

{% block title %}Página Inicial{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
{#                    <div class="card-header">Entrar no sistema</div>#}
                    <div class="card-body">
                        <div class="jumbotron">
                            <h1>Bem-vindo à Página Inicial</h1>
                            <p>Este é o conteúdo da página inicial</p>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
        .perfil{
            display: none;
        }
    </style>
{% endblock %}

templates/linha_usuario.html
<nav class="navbar" style=" color: white; padding: 0;">
  {% load static %}

    <div class="header-container" style="width: 100%;">

        <div class="container-fluid">
            <div class="navbar" style="justify-content: normal;">
                <a class="navbar-brand text-white" href="#">
                    <img src="{% static 'imagens/logo_ufac_2.png' %}"/>
                </a>
                <span class="topo">
                    <h4>Sistema Médico Pericial<br>Universidade Federal do Acre</h4>
                </span>
            </div>

            <div class="perfil">
                <div class="card-user">
                    <div class="card_load">
                        <img src="{% static 'imagens/user.png' %}" alt=""/>
                    </div>
                    
                    {# Comentei o código anterior e ajustei para este #}
                    {% if profissional_saude %}
                        <div class="d-flex flex-column" id="card_title">
                            <span class="text-black" style="font-size: 14px; font-weight: bold">
                                {{ profissional_saude.area }}
                                &nbsp;&nbsp;<i class="fa fa-user-md" style="font-size: 18px"></i>
                            </span>
                            <hr style="margin: 3px">
                            <span class="text-black">
                                {{ profissional_saude.nome }}
                            </span>
                        </div>
                    {% elif administrativo %}
                        <div class="d-flex flex-column" id="card_title">
                            <span class="text-black" style="font-size: 14px; font-weight: bold">
                                {{ administrativo.cargo_funcao }}&nbsp;&nbsp;<i class="fa fa-user"></i>
                            </span>
                            <hr style="margin: 3px">
                            <span class="text-black">
                                {{ administrativo.nome }}
                            </span>
                        </div>
                    {% endif %}
                

                    {# {% if profissional_saude %}#}
                    {#     <div class="d-flex align-items-center" id="card_title">#}
                    {#       <span class="text-black"#}
                    {#             style="padding-left: 10px; font-size: 14px;">{{ profissional_saude.area }}</span>#}
                    {#     </div>#}
                    {# {% elif administrativo %}#}
                    {##}
                    {#     <div class="d-flex align-items-center" id="card_title">#}
                    {#       <span class="text-black"#}
                    {#             style="padding-left: 10px; font-size: 14px;">{{ administrativo.cargo_funcao }}</span>#}
                    {#     </div>#}
                    {# {% endif %}#}
                    {##}
                    {# {% if profissional_saude %}#}
                    {#     <div class="d-flex align-items-center" id="card_descripion">#}
                    {#         <span class="text-black" style="padding-left: 10px;">{{ profissional_saude.nome }}</span>#}
                    {#     </div>#}
                    {##}
                    {# {% elif administrativo %}#}
                    {##}
                    {#     <div class="d-flex align-items-center" id="card_descripion">#}
                    {#         <span class="text-black" style="padding-left: 10px;">{{ administrativo.nome }}</span>#}
                    {#     </div>#}
                    {# {% endif %}#}

                </div>

                <ul class="drop">
                    <li><a href="#">Meu perfil&nbsp;&nbsp;<i class="fa fa-user"></i></a></li>

                    <li style="border-radius: 5px;">
                        <a href="{% url 'sair' %}">
                            Sair&nbsp;&nbsp;<i class="fa fa-sign-out"></i>
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    
        <nav class="links" style="--items: 5;">
          <a href="{% url 'agendamentoListagem' %}">Agendamentos</a>
          <a href="{% url 'listaAtendimentos' %}">Atendimentos</a>
          <a href="{% url 'administrativoListagem' %}">Administrativo</a>
          <a href="{% url 'pacienteListagem' %}">Pacientes</a>
          <a href="{% url 'profissionaldasaudeListagem' %}">Profissional de Saúde</a>
          <span class="line"></span>
        </nav>
  </div>
  

  <nav class="fixed-menu" style="--items: 5;">
    <a href="{% url 'agendamentoListagem' %}">Agendamentos</a>
    <a href="{% url 'listaAtendimentos' %}">Atendimentos</a>
    <a href="{% url 'administrativoListagem' %}">Administrativo</a>
    <a href="{% url 'pacienteListagem' %}">Pacientes</a>
    <a href="{% url 'profissionaldasaudeListagem' %}">Profissional de Saúde</a>
    <span class="line"></span>
  </nav>
  
</nav>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const headerContainer = document.querySelector('.header-container');
    const fixedMenu = document.querySelector('.fixed-menu');
    const headerHeight = headerContainer.offsetHeight;
  
    window.addEventListener('scroll', () => {
      if (window.scrollY > headerHeight) {
        fixedMenu.classList.add('visible'); // Adiciona a classe 'visible' para mostrar o menu
      } else {
        fixedMenu.classList.remove('visible'); // Remove a classe 'visible' para esconder o menu
      }
    });
  });
</script>

<style>

  
</style>

templates/mensagens.html

{% for message in messages %}
{#    <div class="messages" style="padding-left: 0 !important;">#}
    {% if message.tags == 'success' %}
         <ul class="list-unstyled">
                <li class="list-group-item-success">
                    <strong>{{ message }}</strong>
                </li>
            </ul>
    {% endif %}

    {% if message.tags == 'error' %}
        <div class="alert alert-danger">

                    <strong>{{ message }}</strong>

        </div>
    {% endif %}

        {% if message.tags == 'warning' %}
        <div class="alert alert-warning">
            <ul class="list-unstyled">
                <li class="list-group-item-warning">
                    <strong>{{ message }}</strong>
                </li>
            </ul>
        </div>
    {% endif %}



{#    </div>#}


{% endfor %}

templates/messages.html

{% for message in messages %}

{#    <div class="messages" style="padding-left: 0 !important;">#}

    {% if message.tags == 'success' %}
         <div class="alert alert-success">
             <strong>{{ message }}</strong>
         </div>
    {% endif %}

    {% if message.tags == 'error' %}
        <div class="alert alert-danger">
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

        {% if message.tags == 'warning' %}
        <div class="alert alert-warning">
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

{#    </div>#}

{% endfor %}